### ISSUE TITLE
Monitor network traffic of different PC?

### ISSUE THREAD

**Issue by mattbruman** [ericgla/RTC-Call-Monitor#4]
My work computer wont allow me to install the RTC call service as I don't have admin rights, is there a way to monitor all network traffic to watch for meeting traffic?

**Comment by ericgla** [comment]
I don't think it will be possible.  Creating an instance of `System.Net.Sockets.Socket` in `NetworkListener.cs` also requires admin rights.

**Comment by mattbruman** [comment]
> I don't think it will be possible. Creating an instance of `System.Net.Sockets.Socket` in `NetworkListener.cs` also requires admin rights.

What about using wireshark api to trigger the webhook? I'm not a expert in network monitoring but maybe there is a way?

**Comment by ericgla** [comment]
I would assume Wireshark would need admin rights as well in order to do any packet capture.

**Comment by mattbruman** [comment]
> I would assume Wireshark would need admin rights as well in order to do any packet capture.

I would run it on my server that I do have admin rights on and then monitor network traffic on the whole network.

**Comment by ericgla** [comment]
out of scope
